version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: karma-firefox-launcher
    versions:
    - "> 1.1.0"
  - dependency-name: karma-sauce-launcher
    versions:
    - "> 1.2.0"
  - dependency-name: rollup
    versions:
    - "> 0.67.4"
  - dependency-name: jasmine
    versions:
    - 3.6.4
