name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm build        
        npm run test:lint
        npm run test:spec:node
      env:
        CI: true
    - name: check dist is up to date
      run: |
        git add . # make sure line endings are sanitized by git
        git diff HEAD --exit-code
